const fetchResultsResponse = '''
{
  "total_count": 1,
  "incomplete_results": false,
  "items": [
    {
      "id": 395118676,
      "node_id": "MDEwOlJlcG9zaXRvcnkzOTUxMTg2NzY=",
      "name": "SQL-and-Power-BI-Business-Case",
      "full_name": "MalikSullins/SQL-and-Power-BI-Business-Case",
      "private": false,
      "owner": {
        "login": "MalikSullins",
        "id": 73730072,
        "node_id": "MDQ6VXNlcjczNzMwMDcy",
        "avatar_url": "https://avatars.githubusercontent.com/u/73730072?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/MalikSullins",
        "html_url": "https://github.com/MalikSullins",
        "followers_url": "https://api.github.com/users/MalikSullins/followers",
        "following_url": "https://api.github.com/users/MalikSullins/following{/other_user}",
        "gists_url": "https://api.github.com/users/MalikSullins/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/MalikSullins/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/MalikSullins/subscriptions",
        "organizations_url": "https://api.github.com/users/MalikSullins/orgs",
        "repos_url": "https://api.github.com/users/MalikSullins/repos",
        "events_url": "https://api.github.com/users/MalikSullins/events{/privacy}",
        "received_events_url": "https://api.github.com/users/MalikSullins/received_events",
        "type": "User",
        "site_admin": false
      },
      "html_url": "https://github.com/MalikSullins/SQL-and-Power-BI-Business-Case",
      "description": "Business Summary, Query1, Query2, Query3, Model, Dashboard",
      "fork": false,
      "url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case",
      "forks_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/forks",
      "keys_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/keys{/key_id}",
      "collaborators_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/collaborators{/collaborator}",
      "teams_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/teams",
      "hooks_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/hooks",
      "issue_events_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/issues/events{/number}",
      "events_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/events",
      "assignees_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/assignees{/user}",
      "branches_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/branches{/branch}",
      "tags_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/tags",
      "blobs_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/git/blobs{/sha}",
      "git_tags_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/git/tags{/sha}",
      "git_refs_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/git/refs{/sha}",
      "trees_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/git/trees{/sha}",
      "statuses_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/statuses/{sha}",
      "languages_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/languages",
      "stargazers_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/stargazers",
      "contributors_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/contributors",
      "subscribers_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/subscribers",
      "subscription_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/subscription",
      "commits_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/commits{/sha}",
      "git_commits_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/git/commits{/sha}",
      "comments_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/comments{/number}",
      "issue_comment_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/issues/comments{/number}",
      "contents_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/contents/{+path}",
      "compare_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/compare/{base}...{head}",
      "merges_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/merges",
      "archive_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/{archive_format}{/ref}",
      "downloads_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/downloads",
      "issues_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/issues{/number}",
      "pulls_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/pulls{/number}",
      "milestones_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/milestones{/number}",
      "notifications_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/notifications{?since,all,participating}",
      "labels_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/labels{/name}",
      "releases_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/releases{/id}",
      "deployments_url": "https://api.github.com/repos/MalikSullins/SQL-and-Power-BI-Business-Case/deployments",
      "created_at": "2021-08-11T21:17:16Z",
      "updated_at": "2021-08-11T21:21:49Z",
      "pushed_at": "2021-08-11T21:18:11Z",
      "git_url": "git://github.com/MalikSullins/SQL-and-Power-BI-Business-Case.git",
      "ssh_url": "git@github.com:MalikSullins/SQL-and-Power-BI-Business-Case.git",
      "clone_url": "https://github.com/MalikSullins/SQL-and-Power-BI-Business-Case.git",
      "svn_url": "https://github.com/MalikSullins/SQL-and-Power-BI-Business-Case",
      "homepage": "",
      "size": 681,
      "stargazers_count": 0,
      "watchers_count": 0,
      "language": null,
      "has_issues": true,
      "has_projects": true,
      "has_downloads": true,
      "has_wiki": true,
      "has_pages": false,
      "forks_count": 0,
      "mirror_url": null,
      "archived": false,
      "disabled": false,
      "open_issues_count": 0,
      "license": null,
      "allow_forking": true,
      "is_template": false,
      "topics": [

      ],
      "visibility": "public",
      "forks": 0,
      "open_issues": 0,
      "watchers": 0,
      "default_branch": "main",
      "score": 1.0
    }
  ]
}

''';
